version: "3"

services:
  #MongoDB
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - 5000:5000
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: mongodb+srv://chathurad:asdffdsa@cluster-1.229jd5b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster-1

    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
#run command
# docker compose up